// <auto-generated />
using Checkpromise.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Checkpromise.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190428081042_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Checkpromise.Models.Chart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Source");

                    b.HasKey("Id");

                    b.ToTable("Chart");
                });

            modelBuilder.Entity("Checkpromise.Models.Promise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<string>("Description");

                    b.Property<string>("Source");

                    b.HasKey("Id");

                    b.ToTable("Promise");
                });
#pragma warning restore 612, 618
        }
    }
}
